apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../proofs

images:
- name: 000000000000.dkr.ecr.us-west-2.amazonaws.com/kairo/proof-worker
  newName: host.docker.internal:4566/kairo/proof-worker
  newTag: local

patches:
- target:
    kind: Deployment
    name: proof-worker
    namespace: kairo
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: Kairo
