apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-model-cache
  namespace: kairo
  labels:
    app.kubernetes.io/part-of: Kairo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
